//DEFINIR (CRIAR) ALGUMAS VARIÁVEIS DE MOVIMENTAÇÃO
hspd = -1;		//MOVIMENTAÇÃO HORIZONTAL
vspd = -1;		//MOVIMENTAÇÃO VERTICAL

jumpSpd = 12;	//VELOCIDADE DE PULO
walkSpd = 8;	//VELOCIDADE DE MOVIMENTO AO ANDAR
spd = walkSpd;	//VELOCIDADE DE MOVIMENTO ATUAL

//DEFINIR OS 'INPUTS'
right = -1;		//INPUT DE ANDAR PARA DIREITA
left = -1;		//INPUT DE ANDAR PARA ESQUERDA
jump = -1;		//INPUT DE PULAR

//DEFINIR AÇÕES
isOnFloor = false;	//VERIFICA SE O JOGADOR ESTÁ NO CHÃO OU NÃO

//VARIÁVEIS DE GRAVIDADE
#macro GRAVITY 0.25
density = 1;		//VALOR DE DENSIDADE, QUANTO MAIOR A DENSIDADE, MAIS RÁPIDO ELE SOFRE A FORÇA DA GRAVIDADE